CREATE TABLE STUDENTS(
    SID INTEGER,
    Name VARCHAR2(100),
    Major VARCHAR2(100),
    PRIMARY KEY(SID)
);

CREATE TABLE PROJECTS(
    PID INTEGER,
    P_Name VARCHAR2(100),
    PRIMARY KEY(PID)
);

CREATE TABLE COURSES(
    CID INTEGER,
    C_Name VARCHAR2(100),
    PRIMARY KEY(CID)
);

CREATE TABLE MEMBERS(
    PID INTEGER,
    SID INTEGER,
    PRIMARY KEY (PID, SID),
    FOREIGN KEY (PID) REFERENCES PROJECTS(PID),
    FOREIGN KEY (SID) REFERENCES STUDENTS(SID)
);

CREATE TABLE ENROLLMENTS(
    CID INTEGER,
    SID INTEGER,
    PRIMARY KEY (CID, SID),
    FOREIGN KEY (CID) REFERENCES COURSES(CID),
    FOREIGN KEY (SID) REFERENCES STUDENTS(SID)
);