INSERT INTO Students
VALUES (0, 'TYLER', 'CS');

INSERT INTO Students
VALUES (1, 'JEFF', 'CS');

INSERT INTO Students
VALUES (2, 'AMY', 'ART');

INSERT INTO Students
VALUES (3, 'BOB', 'MATH');

INSERT INTO Students
VALUES (4, 'CAM', 'EE');

INSERT INTO Courses
VALUES (0, 'EECS 183');

INSERT INTO Courses
VALUES (1, 'EECS 281');

INSERT INTO Enrollments (SID, CID)
VALUES (0, 0);

INSERT INTO Enrollments (SID, CID)
VALUES (1, 0);