INSERT INTO Students
VALUES (0, 'TYLER', 'CS');

INSERT INTO Students
VALUES (1, 'JEFF', 'CS');

INSERT INTO Students
VALUES (2, 'AMY', 'ART');

INSERT INTO Students
VALUES (3, 'BOB', 'MATH');

INSERT INTO Students
VALUES (4, 'CAM', 'EE');

INSERT INTO Students
VALUES (5, 'DAVID', 'CS');

INSERT INTO Students
VALUES (6, 'EDWARD', 'CS');

INSERT INTO Courses
VALUES (0, 'EECS 183');

INSERT INTO Courses
VALUES (1, 'EECS 484');

INSERT INTO Enrollments
VALUES (6, 0);

INSERT INTO Enrollments
VALUES (5, 0);

INSERT INTO Enrollments
VALUES (4, 0);

INSERT INTO Enrollments
VALUES (0, 1);

INSERT INTO Enrollments
VALUES (1, 1);

INSERT INTO Enrollments
VALUES (2, 0);

INSERT INTO Enrollments
VALUES (3, 0);